name: Build Catalyst UI (A146B)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run build
        run: |
          chmod -R +x scripts/
          chmod +x build_catalyst.sh
          ./build_catalyst.sh

      - name: Upload AP artifact
        uses: actions/upload-artifact@v4
        with:
          name: CatalystUI_A146B_Release
          path: out/*.tar.md5
          if-no-files-found: error
